[package]
name = "gitter"
version = "0.1.0"
authors = ["shmutalov <shmutalov@gmail.com>"]

description = "A library that provides Gitter API"

keywords = ["gitter", "api", "chat"]
license = "MIT"

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
tokio-core = "0.1"
error-chain = "0.10.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.hyper-tls]
git = "https://github.com/hyperium/hyper-tls.git"