[package]
name = "gitter"
version = "0.1.0"
authors = ["shmutalov <shmutalov@gmail.com>"]

description = "A library that provides Gitter API"

keywords = ["gitter", "api", "chat"]
license = "MIT"

[dependencies]
chrono = { version = "=0.3.0", features = ["serde"] }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
serde_urlencoded = "0.4"
reqwest = "0.5.1"
